// ============================================================
// materias.js  –  Datos de la Malla QF PE2015 · UDELAR
// Editá este archivo para modificar previas, créditos, etc.
// ============================================================

const areasMeta = {
  CFM: { nombre: "Ciencias Físico-Matemáticas",      creditosMin: 42,  color: "#2563EB", colorPastel: "#DBEAFE" },
  CQ:  { nombre: "Ciencias Químicas",                creditosMin: 108, color: "#16A34A", colorPastel: "#DCFCE7" },
  CBB: { nombre: "Ciencias Biológicas y Biomédicas", creditosMin: 69,  color: "#EA580C", colorPastel: "#FFEDD5" },
  CFA: { nombre: "Ciencias Farmacéuticas",           creditosMin: 105, color: "#7C3AED", colorPastel: "#EDE9FE" },
  PRO: { nombre: "Practicantado",                    creditosMin: 55,  color: "#475569", colorPastel: "#F1F5F9" },
  OPE: { nombre: "Optativas y Electivas",            creditosMin: 71,  color: "#DB2777", colorPastel: "#FCE7F3" },
};

const CREDITOS_MIN = 450;

// pre: IDs de previas requeridas (todas exoneradas, según PDF oficial PE2015)
// hemisemestre: 1 = primer hemi | 2 = segundo hemi | null = semestre completo
const materias = [
  // ── SEMESTRE 1 ─────────────────────────────────────────────────────────
  { id:"MAT_A",      codigo:"01A",  semestre:1, hemisemestre:null,
    nombre:"Matemática A",               abrev:"Mat. A",    area:"CFM", creditos:10, pre:[] },
  { id:"QUI_GEN_I",  codigo:"102",  semestre:1, hemisemestre:null,
    nombre:"Química General I",          abrev:"Q. Gral. I", area:"CQ", creditos:7,  pre:[] },
  { id:"BIO_I",      codigo:"103B", semestre:1, hemisemestre:null,
    nombre:"Introd. Cs. Biológicas I",   abrev:"ICB I",     area:"CBB", creditos:5,  pre:[] },
  { id:"RIESGOS",    codigo:"104A", semestre:1, hemisemestre:2,
    nombre:"Prev. de Riesgos en Lab.",   abrev:"Prev. Riesgos", area:"CQ", creditos:4, pre:[],
    notas:"2do hemisemestre" },

  // ── SEMESTRE 2 ─────────────────────────────────────────────────────────
  { id:"MAT_B",      codigo:"02B",  semestre:2, hemisemestre:1,
    nombre:"Matemática B",               abrev:"Mat. B",    area:"CFM", creditos:6,
    pre:["MAT_A"], notas:"Álgebra Lineal y Análisis Multivariable. 1er hemisemestre" },
  { id:"MAT_C",      codigo:"02C",  semestre:2, hemisemestre:null,
    nombre:"Matemática C",               abrev:"Mat. C",    area:"CFM", creditos:8,
    pre:["MAT_A"], notas:"Estadística" },
  { id:"QUI_GEN_II", codigo:"202",  semestre:2, hemisemestre:null,
    nombre:"Química General II",         abrev:"Q. Gral. II", area:"CQ", creditos:8,
    pre:["QUI_GEN_I","RIESGOS"] },
  { id:"BIO_II",     codigo:"203A", semestre:2, hemisemestre:null,
    nombre:"Introd. Cs. Biológicas II",  abrev:"ICB II",    area:"CBB", creditos:5,
    pre:["BIO_I","RIESGOS"] },
  { id:"FIS101",     codigo:"205Q", semestre:2, hemisemestre:null,
    nombre:"Física 101",                 abrev:"Física 101",area:"CFM", creditos:7,
    pre:["MAT_A"] },

  // ── SEMESTRE 3 ─────────────────────────────────────────────────────────
  { id:"QO101",      codigo:"301",  semestre:3, hemisemestre:null,
    nombre:"Química Orgánica 101",       abrev:"Org. 101",  area:"CQ", creditos:11,
    pre:["QUI_GEN_II"] },
  { id:"QA1",        codigo:"302",  semestre:3, hemisemestre:null,
    nombre:"Química Analítica I",        abrev:"Q. Anal. I",area:"CQ", creditos:10,
    pre:["QUI_GEN_II"] },
  { id:"QI_T",       codigo:"303A", semestre:3, hemisemestre:null,
    nombre:"Química Inorgánica (T)",     abrev:"Q. Inorg. T",area:"CQ", creditos:6,
    pre:["QUI_GEN_II"], notas:"Teórico" },
  { id:"QI_L",       codigo:"303B", semestre:3, hemisemestre:null,
    nombre:"Lab. de Química Inorgánica", abrev:"Q. Inorg. L",area:"CQ", creditos:5,
    pre:["QUI_GEN_II"], notas:"Laboratorio" },
  { id:"FIS102",     codigo:"304Q", semestre:3, hemisemestre:null,
    nombre:"Física 102",                 abrev:"Física 102",area:"CFM", creditos:7,
    pre:["FIS101"], notas:"Electromagnetismo" },
  { id:"FISIO",      codigo:"408A", semestre:3, hemisemestre:null,
    nombre:"Fisiología",                 abrev:"Fisiología",area:"CBB", creditos:7,
    pre:["BIO_II"] },

  // ── SEMESTRE 4 ─────────────────────────────────────────────────────────
  { id:"QO102",      codigo:"401",  semestre:4, hemisemestre:null,
    nombre:"Química Orgánica 102",       abrev:"Org. 102",  area:"CQ", creditos:6,
    pre:["QO101"] },
  { id:"QA2",        codigo:"402A", semestre:4, hemisemestre:null,
    nombre:"Química Analítica II",       abrev:"Q. Anal. II",area:"CQ", creditos:7,
    pre:["QA1"] },
  { id:"FQ102",      codigo:"508A", semestre:4, hemisemestre:null,
    nombre:"Fisicoquímica 102",          abrev:"FQ 102",    area:"CQ", creditos:13,
    pre:["MAT_B","QA1"] },
  { id:"FIS003L",    codigo:"404",  semestre:4, hemisemestre:1,
    nombre:"Física 003 (L)",             abrev:"Física 003L",area:"CFM", creditos:4,
    pre:["FIS102"], notas:"Laboratorio. 1er hemisemestre" },
  { id:"FISIOPAT",   codigo:"415C", semestre:4, hemisemestre:null,
    nombre:"Fisiopatología",             abrev:"Fisiopatol.",area:"CBB", creditos:7,
    pre:["FISIO"] },
  { id:"INTRO_MED",  codigo:"416X", semestre:4, hemisemestre:1,
    nombre:"Introducción al Medicamento",abrev:"Intro. Med.",area:"CFA", creditos:2,
    pre:[], notas:"1er hemisemestre. Asistencia obligatoria." },

  // ── SEMESTRE 5 ─────────────────────────────────────────────────────────
  { id:"QO103L",     codigo:"501",  semestre:5, hemisemestre:null,
    nombre:"Q. Orgánica 103 (L)",        abrev:"Org. 103L", area:"CQ", creditos:5,
    pre:["QO101","QA1"], notas:"Laboratorio" },
  { id:"QO104",      codigo:"502X", semestre:5, hemisemestre:1,
    nombre:"Química Orgánica 104",       abrev:"Org. 104",  area:"CQ", creditos:4,
    pre:["QO102"], notas:"1er hemisemestre" },
  { id:"QA3",        codigo:"503",  semestre:5, hemisemestre:null,
    nombre:"Química Analítica III",      abrev:"Q. Anal. III",area:"CQ", creditos:10,
    pre:["QA2"], notas:"Análisis Instrumental" },
  { id:"FQ103",      codigo:"520A", semestre:5, hemisemestre:null,
    nombre:"Fisicoquímica 103",          abrev:"FQ 103",    area:"CQ", creditos:12,
    pre:["FQ102"] },
  { id:"BIOQ",       codigo:"190",  semestre:5, hemisemestre:null,
    nombre:"Bioquímica Op. II",          abrev:"Bioquímica",area:"CBB", creditos:10,
    pre:["BIO_I","FQ102","QO102","QA2"], notas:"Código 190, a partir de 2026" },

  // ── SEMESTRE 6 ─────────────────────────────────────────────────────────
  { id:"FARMACOGNOSIA",   codigo:"909",  semestre:6, hemisemestre:null,
    nombre:"Farmacognosia",              abrev:"Farmacogn.", area:"CFA", creditos:9,
    pre:["QO103L","QO104","QA3"] },
  { id:"BOTANICA",        codigo:"908A", semestre:6, hemisemestre:1,
    nombre:"Botánica",                   abrev:"Botánica",  area:"CFA", creditos:4,
    pre:["BIO_II","QO103L","QO104","QA3"], notas:"1er hemisemestre" },
  { id:"MICROBIO_T",      codigo:"533T", semestre:6, hemisemestre:null,
    nombre:"Microbiología Gral. (T)",    abrev:"Microbio. T",area:"CBB", creditos:6,
    pre:["BIO_II","BIOQ"], notas:"Teórico" },
  { id:"MICROBIO_L",      codigo:"533L", semestre:6, hemisemestre:null,
    nombre:"Lab. Análisis Microbiol.",   abrev:"Microbio. L",area:"CBB", creditos:6,
    pre:["BIO_I","BIOQ"], notas:"Laboratorio" },
  { id:"INMUNO1",         codigo:"506X", semestre:6, hemisemestre:2,
    nombre:"Inmunología I",              abrev:"Inmuno. I", area:"CBB", creditos:5,
    pre:["BIO_II","BIOQ"], notas:"2do hemisemestre" },
  { id:"FARMACOKINETICA", codigo:"535X", semestre:6, hemisemestre:null,
    nombre:"Farmacocinética y Biofarmacia",abrev:"Farmacocin.",area:"CFA", creditos:8,
    pre:["FISIO","MAT_B"] },
  { id:"TALLER_INTEG",    codigo:"615",  semestre:6, hemisemestre:1,
    nombre:"Taller Integ. Cs. Bio. y Biomed.",abrev:"Taller Integ.",area:"CBB", creditos:2,
    pre:["FISIO","FISIOPAT"], notas:"1er hemisemestre" },
  { id:"UC_CALIDAD",      codigo:"157",  semestre:6, hemisemestre:2,
    nombre:"Sistemas de Gestión",        abrev:"Sist. Gestión",area:"CFA", creditos:4,
    pre:["MAT_C","QA3"], notas:"2do hemisemestre. A partir de 2025." },

  // ── SEMESTRE 7 ─────────────────────────────────────────────────────────
  { id:"QF101",    codigo:"700",  semestre:7, hemisemestre:null,
    nombre:"Química Farmacéutica 101 (T)", abrev:"Q. Farm. 101",area:"CFA", creditos:8,
    pre:["QO102","QO103L","QO104","QA3","FQ102","FARMACOGNOSIA","BIOQ"], notas:"Teórico" },
  { id:"QF102",    codigo:"701X", semestre:7, hemisemestre:null,
    nombre:"Química Farmacéutica 102 (L)", abrev:"Q. Farm. 102",area:"CFA", creditos:6,
    pre:["QO102","QO103L","QO104","QA3","FQ102","FQ103","FARMACOGNOSIA","BIOQ"], notas:"Laboratorio" },
  { id:"FTEC1",    codigo:"702X", semestre:7, hemisemestre:null,
    nombre:"Farmacotecnia I",              abrev:"Farmacotec. I",area:"CFA", creditos:10,
    pre:["FARMACOKINETICA","FARMACOGNOSIA","BOTANICA","MICROBIO_T","QA3","QI_T","FQ102","INTRO_MED"] },
  { id:"FARMACO",  codigo:"703X", semestre:7, hemisemestre:null,
    nombre:"Farmacología",                 abrev:"Farmacología",area:"CFA", creditos:10,
    pre:["QO102","QO103L","QO104","FISIO","TALLER_INTEG","BIOQ"] },
  { id:"INMUNO2",  codigo:"534X", semestre:7, hemisemestre:null,
    nombre:"Inmunología II",               abrev:"Inmuno. II",area:"CBB", creditos:7,
    pre:["INMUNO1"] },
  { id:"BROMATO",  codigo:"704",  semestre:7, hemisemestre:2,
    nombre:"Bromatología y Nutrición",     abrev:"Bromatología",area:"CBB", creditos:4,
    pre:["BIOQ","MICROBIO_T"], notas:"2do hemisemestre" },

  // ── SEMESTRE 8 ─────────────────────────────────────────────────────────
  { id:"FARMACOTERAPIA", codigo:"803X", semestre:8, hemisemestre:null,
    nombre:"Farmacoterapia I",             abrev:"Farmacoterap.",area:"CFA", creditos:8,
    pre:["FISIOPAT","FARMACO"] },
  { id:"FTEC2",          codigo:"802X", semestre:8, hemisemestre:null,
    nombre:"Farmacotecnia II",             abrev:"Farmacotec. II",area:"CFA", creditos:10,
    pre:["FTEC1"] },
  { id:"CONTROL",        codigo:"804X", semestre:8, hemisemestre:null,
    nombre:"Control de Calidad Medic. I",  abrev:"Control Cal.",area:"CFA", creditos:12,
    pre:["MICROBIO_T","QF101","QF102","FTEC1"] },
  { id:"TOXICO",         codigo:"805",  semestre:8, hemisemestre:1,
    nombre:"Toxicología Fundamental",      abrev:"Toxicología",area:"CFA", creditos:4,
    pre:["QA3","BIOQ"], notas:"1er hemisemestre" },

  // ── SEMESTRE 9 ─────────────────────────────────────────────────────────
  { id:"LEGISLACION", codigo:"809", semestre:9, hemisemestre:null,
    nombre:"Legislación y Deontología",    abrev:"Legislación",area:"CFA", creditos:6,
    pre:["FTEC2","FARMACOTERAPIA"] },
  { id:"GESTION",     codigo:"410", semestre:9, hemisemestre:2,
    nombre:"Gestión de Empresas",          abrev:"Gestión Emp.",area:"CFA", creditos:4,
    pre:[], notas:"2do hemisemestre. Asistencia controlada." },

  // ── SEMESTRE 10 ────────────────────────────────────────────────────────
  { id:"PRACTICA", codigo:"965X", semestre:10, hemisemestre:null,
    nombre:"Practicantado",                abrev:"Practicantado",area:"PRO", creditos:55,
    pre:[], notas:"Requiere todas las obligatorias aprobadas." },
];
